global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  # Prometheus service
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus.iotakingdoms.com:9090']

  # Grafana service
  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana.iotakingdoms.com:3000']

  # Auth service
  - job_name: 'auth'
    scrape_interval: 5s
    static_configs:
      - targets: ['auth.iotakingdoms.com:8080']

  # Example job for node_exporter
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100']

  # Example job for cadvisor
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
